"""empty message

Revision ID: ba84c8d31aca
Revises: 7ff2359e3bb7
Create Date: 2020-03-11 21:47:55.076466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba84c8d31aca'
down_revision = '7ff2359e3bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues_shows_artists')
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'artist_id')
    op.create_table('venues_shows_artists',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='venues_shows_artists_artist_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='venues_shows_artists_show_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='venues_shows_artists_venue_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'show_id', 'venue_id', name='venues_shows_artists_pkey')
    )
    # ### end Alembic commands ###
